Bump Bifrost 1.0.5
brewsci/homebrew-bio pull request #1159
Opened 2020-09-19 21:38 UTC by GuillaumeHolley

- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

2020-09-30 23:18 UTC, sjackman requested changes

2020-09-30 23:18 UTC, sjackman commented on Formula/bifrost.rb
> +  url "https://github.com/pmelsted/bifrost/archive/v1.0.5.tar.gz"
Please update the `sha256`. Running `brew fetch -s bifrost` will tell you the new SHA-256.

2020-09-30 23:18 UTC, sjackman commented on Formula/bifrost.rb
> +    sha256 "47360fe757b4aeec438deb38449dcaad607fc7421e7d6bf819112c8ed58c0d5d" => :x86_64_linux
Please revert this chunk of changes.

2020-11-12 03:37 UTC, SeekingMeaning approved these changes

2020-11-12 03:39 UTC, merged