hssp 3.1.5 (new formula)
brewsci/homebrew-bio pull request #1189
Opened 2020-11-04 05:31 UTC by YoshitakaMo

- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?
-----

This is a new formula of hssp. 
I also suggest that `xssp.rb` formula should be deprecated because two programs `mkdssp` and `mkhssp` installed by `brew install xssp` are now managed independently.

2020-11-04 06:15 UTC, YoshitakaMo commented
The Build bottles said:
```
==> brew audit --tap=brewsci/bio
==> FAILED
Error: 2 problems in 2 formulae detected
brewsci/bio/seqan@2:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio/Aliases
      ln -s ../Formula/seqan@2.rb seqan@2@2
brewsci/bio/seqan@3:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio/Aliases
      ln -s ../Formula/seqan@3.rb seqan@3@3
```
I don't have any idea to solve this issue...

2020-11-04 06:22 UTC, sjackman commented
That's a bug in Homebrew, that I thought was fixed. I'll look into it and get back to you.

2020-11-10 06:30 UTC, sjackman requested changes

2020-11-10 06:30 UTC, sjackman commented on Formula/hssp.rb
> +  end
```suggestion
```
You can delete the bottle block. It is added by CI after the bottles are built.

2020-11-10 06:31 UTC, sjackman commented on Formula/hssp.rb
> +  depends_on "boost"
Is there run-time linkage to `boost`? What's the output of `brew linkage boost`?

2020-11-10 06:36 UTC, sjackman commented on Formula/hssp.rb
> +  end
Where did this bottle block come from?

2020-11-11 08:13 UTC, YoshitakaMo commented
Here is the output.
```
$ brew linkage hssp
System libraries:
  /usr/lib/libSystem.B.dylib
  /usr/lib/libc++.1.dylib
Homebrew libraries:
  /usr/local/opt/boost/lib/libboost_date_time-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_filesystem.dylib (boost)
  /usr/local/opt/boost/lib/libboost_iostreams-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_program_options-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_regex-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_system.dylib (boost)
  /usr/local/opt/boost/lib/libboost_thread-mt.dylib (boost)
  /usr/local/opt/boost/lib/libboost_timer.dylib (boost)
  /usr/local/opt/boost/lib/libboost_unit_test_framework-mt.dylib (boost)
```

But another issue happened on the build-linux-bottles.
```
==> Running Formulae#formula!(brewsci/bio/hssp)
==> Determining dependencies...
==> brew fetch --retry autoconf automake berkeley-db boost bzip2 expat gdbm libbsd m4 openssl@1.1 perl xz zlib
==> Determining dependents...
==> brew uninstall --force autoconf automake berkeley-db boost bzip2 expat gdbm libbsd m4 openssl@1.1 perl xz zlib
Error: Failure while executing; `brew uses --include-build --include-test --recursive brewsci/bio/hssp` exited with 1. Here's the output:
Error: Process completed with exit code 1.
```

2020-11-12 00:52 UTC, sjackman commented
`Error: Failure while executing; `brew uses --include-build --include-test --recursive brewsci/bio/hssp` exited with 1.`

Sigh. It's not a good day for CI. I'll look into it.

2020-11-12 17:55 UTC, sjackman approved these changes

2020-11-12 17:56 UTC, merged