matplotlib 3.3.3
brewsci/homebrew-bio pull request #1249
Opened 2021-01-21 14:31 UTC by sumanthratna

- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

2021-01-21 21:11 UTC, sumanthratna commented
@SeekingMeaning ready for review! 
- removes an unnecessary python dep (tabulate) in kat, since Python functionality isn't installed
- bumps matplotlib and removes an unnecessary requirement

2021-01-24 06:53 UTC, sjackman commented
Thanks for this work, Sumanth! Could you please squash it down to two commits, one for `matplotlib` and one for `kat`? Happy to explain further if you need more detailed instructions on how to squash. In short, `git rebase -i origin/master` is your friend.

2021-01-24 16:18 UTC, sumanthratna commented
> Thanks for this work, Sumanth! Could you please squash it down to two commits, one for `matplotlib` and one for `kat`? Happy to explain further if you need more detailed instructions on how to squash. In short, `git rebase -i origin/master` is your friend.

Sure! I know how to rebase :) one quick question: shouldn't I rebase from the `develop` branch of origin (not `master`)?

2021-01-24 22:39 UTC, sjackman commented
>  one quick question: shouldn't I rebase from the develop branch of origin (not master)?

Yep! The two branches should usually be in sync, except immediately after merging a PR before the bottles have been uploaded, but yes, you're right.

2021-01-24 22:44 UTC, sjackman requested changes

2021-01-24 22:44 UTC, sjackman commented on Formula/matplotlib.rb
> -  end
No need to delete the `bottle do` block. It gets updated automatically by CI. PR looks good otherwise. Thanks!

2021-01-29 19:02 UTC, merged