Updating gatk to 4.2.0.0
brewsci/homebrew-bio pull request #1292
Opened 2021-02-22 22:06 UTC by lbergelson

- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

I've noticed that for some reason I get a new message whenever I do anything like `brew audit` or `brew install` that has a message like this:

```
Error: Failed to load cask: Formula/gatk.rb
Cask 'gatk' is unreadable: wrong constant name #<Class:0x00007faa52059d68>
Warning: Treating Formula/gatk.rb as a formula.
```
It goes away if I specify the `--formula` argument to brew but I'm not sure if there's something that needs to be updated in the formula itself or if it's just a new weird thing that's happening to me.

2021-02-24 23:13 UTC, sjackman commented
Weird. It doesn't look there's a cask for `gatk`. What does `brew formula gatk` and `brew info gatk` report?

2021-02-25 00:46 UTC, sjackman requested changes
Could you please change `depends_on "python@3.8"` to `depends_on "python@3.9"`, assuming that it works with Python 3.9?

2021-03-02 21:05 UTC, lbergelson commented
I updated python to 3.9.

Here are the results of those commands.  Nothing too wierd...
```
🐋 brew formula gatk
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/gatk.rb
```

```
🐋 brew info gatk
brewsci/bio/gatk: stable 4.1.8.1 (bottled)
Genome Analysis Toolkit: Variant Discovery in High-Throughput Sequencing
https://software.broadinstitute.org/gatk
/usr/local/Cellar/gatk/4.2.0.0 (10 files, 462MB) *
  Built from source on 2021-02-22 at 14:44:03
From: https://github.com/brewsci/homebrew-bio/blob/HEAD/Formula/gatk.rb
License: BSD-3-Clause
==> Dependencies
Required: openjdk ✔, python@3.8 ✔
==> Caveats
This brew installation does not include the necessary python dependencies to run certain gatk tools.
Similarly, it does not install the necessary version of R and its packages for certain plotting functions to work.

See the GATK readme for detailed installation instructions.
   https://github.com/broadinstitute/gatk

The recommended way of running the tools with complex python dependencies is to use the pre-built docker images instead of attempting to install them locally.
Gatk dockers are available on docker hub:
   https://hub.docker.com/r/broadinstitute/gatk/tags/
```

2021-03-03 02:57 UTC, merged

2021-03-03 02:57 UTC, sjackman commented
Merged. Thanks again, Louis! 🌟