Bumping version of Kalign to latest available (v3.3.1)
brewsci/homebrew-bio pull request #1385
Opened 2021-08-05 14:42 UTC by biomadeira

- [ x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

2021-08-05 20:29 UTC, sjackman requested changes
Fix the typo.

2021-08-05 20:29 UTC, sjackman commented on Formula/kalign.rb
> +  url "hhttps://github.com/TimoLassmann/kalign/archive/v3.3.1.tar.gz"
```suggestion
  url "https://github.com/TimoLassmann/kalign/archive/v3.3.1.tar.gz"
```
Fix the typo

2021-08-06 14:57 UTC, biomadeira commented
@sjackman Sorry for the typo 😬

2021-08-10 01:00 UTC, sjackman approved these changes

2021-08-10 01:01 UTC, merged

2021-08-10 01:05 UTC, sjackman commented
No worries. Thank you for your first contribution to Brewsci/bio, Fábio! 🥇