eigensoft 8.0.0
brewsci/homebrew-bio pull request #1686
Opened 2024-05-09 21:47 UTC by alexreg

- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

2024-08-02 01:14 UTC, YoshitakaMo requested changes
Thank you for your PR :beer: I've described some suggestions. Please consider them and resubmit to merge.

2024-08-02 01:14 UTC, YoshitakaMo commented on Formula/eigensoft.rb
> +  head "https://github.com/DReichLab/EIG.git"
```suggestion
  head "https://github.com/DReichLab/EIG.git", branch: "master"
```

To solve the error "HEAD: Use `branch: "master"` to specify the default branch", add branch info.

2024-08-02 01:14 UTC, YoshitakaMo commented on Formula/eigensoft.rb
> +  depends_on "openblas"
```suggestion
  depends_on "gsl"
  depends_on "openblas"
```

To solve the linkage error, add 'depends_on "gsl"'.

2024-08-02 01:14 UTC, YoshitakaMo commented on Formula/eigensoft.rb
> +
```suggestion

  def caveats
    "To generate figures, run `brew install gnuplot`."
  end
   
```

One may require gnuplot to work. But it is not necessary for eigensoft itself. I've described caveats for it.

2024-08-08 00:22 UTC, alexreg commented
@YoshitakaMo Thanks for the review. I've incorporated your suggestions now.

2024-08-08 00:37 UTC, merged

2024-08-08 00:37 UTC, YoshitakaMo commented
Merged. Thank you, @alexreg !